version: '3'

services:
    redis_1:
        container_name: redis_1
        build: .
        image: centos-redisha
        tty: true
        stdin_open: true
        ports:
            - '6379:6379'
        command: /bin/bash
        networks:
            static-network:
                ipv4_address: 172.30.0.11
        environment:
            - PORT=6379
            - SENTINEL_MASTER_HOST=redis_1 6379
            - SENTINEL_QUORUM=2
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=5000
    redis_2:
        container_name: redis_2
        build: .
        image: centos-redisha
        tty: true
        stdin_open: true
        command: /bin/bash 
        networks:
            static-network:
                ipv4_address: 172.30.0.12
        ports:
            - '6380:6379'
        environment:
            - PORT=6379
            - SLAVEOF=redis_1 6379  
            - SENTINEL_MASTER_HOST=redis_1 6379
            - SENTINEL_QUORUM=2
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=5000            
        depends_on:
            - redis_1
    redis_3:
        container_name: redis_3
        build: .
        image: centos-redisha
        tty: true
        stdin_open: true
        command: /bin/bash 
        networks:
            static-network:
                ipv4_address: 172.30.0.13
        ports:
            - '6381:6379'
        environment:
            - PORT=6379
            - SLAVEOF=redis_1 6379  
            - SENTINEL_MASTER_HOST=redis_1 6379
            - SENTINEL_QUORUM=2
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=5000            
        depends_on:
            - redis_1
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16    